FROM php:8.1-cli-alpine
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
RUN apk add --update alpine-sdk autoconf

ENTRYPOINT []
WORKDIR /build/
COPY . /build/
RUN phpize && ./configure && make && make install && echo "extension=bprof" > /usr/local/etc/php/conf.d/bprof.ini